defaults: &defaults
  adapter:  postgresql
  encoding: utf-8
  pool:     5
  host:     <%= ENV.fetch "DB_HOST", "127.0.0.1" %>
  port:     <%= ENV.fetch "DB_PORT", "5432" %>
  username: <%= ENV.fetch "DB_USERNAME", "postgres" %>
  password: <%= ENV.fetch "DB_PASSWORD", "postgres" %>

development: &development
  <<: *defaults
  database: quantum_development

test:
  <<: *defaults
  database: quantum_test
